### ISSUE TITLE
Base url is not calculated properly

### ISSUE THREAD

**Issue by toomyem** [bludit/bludit#1110]
### Describe your problem
I tried to install Bludit in Kubernetes. I wanted to configure access to it via http://node.local/bludit path. But I found that links are created with wrong base url. It uses node's ip address in cluster and ignores prefix (/bludit). So the links are created as for example: http://10.42.2.1/about-me, but it should look like: http://node.local/bludit/about-me.

There are headers defined to aid in such situation, like:
```
X-Forwarded-For: 10.42.2.1
X-Forwarded-Host: node.local
X-Forwarded-Port: 80
X-Forwarded-Prefix: /bludit
X-Forwarded-Proto: http
```

Maybe Bludit could use them to properly construct base url?

### Steps to reproduce the problem
Install Bludit as a Pod in Kubernetes and configure Ingress to match service by path, for example as below. (I'm using k3s with has Traefik as default load balancer)

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bludit
  labels:
    app: bludit
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
    - host: node.local
      http:
        paths:
          - path: /bludit
            backend:
              serviceName: bludit
              servicePort: http
```

### Bludit version
3.10.0
